version: "3.8"

services:
  vault:
    image: hashicorp/vault:1.13.3
    container_name: vault
    restart: always
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/data  
    networks:
      - stock_poller_network  

  vault-init:
    image: curlimages/curl
    container_name: vault_init
    depends_on:
      - vault
    entrypoint: ["/bin/sh", "-c", "/vault-init.sh"]
    volumes:
      - ./vault-init.sh:/vault-init.sh:ro  
    networks:
      - stock_poller_network  

  poller:
    build: .
    container_name: stock_data_poller
    depends_on:
      - vault
      - vault-init
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root  
    restart: always
    networks:
      - stock_poller_network  

volumes:
  vault_data:  

networks:
  stock_poller_network:  
    driver: bridge
