version: '3.8'

services:
  poller:
    build: .
    container_name: stock_poller
    environment:
      - POLLER_TYPE=${POLLER_TYPE}
      - POLL_INTERVAL=${POLL_INTERVAL}
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT}
      - MAX_RETRIES=${MAX_RETRIES}
      - RETRY_DELAY=${RETRY_DELAY}
      - LOG_LEVEL=${LOG_LEVEL}
      - POLYGON_API_KEY=${POLYGON_API_KEY}
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
      - YFINANCE_API_KEY=${YFINANCE_API_KEY}
      - IEX_API_KEY=${IEX_API_KEY}
      - QUANDL_API_KEY=${QUANDL_API_KEY}
      - FINNHUB_FILL_RATE_LIMIT=${FINNHUB_FILL_RATE_LIMIT}
      - POLYGON_FILL_RATE_LIMIT=${POLYGON_FILL_RATE_LIMIT}
      - ALPHA_VANTAGE_FILL_RATE_LIMIT=${ALPHA_VANTAGE_FILL_RATE_LIMIT}
      - YFINANCE_FILL_RATE_LIMIT=${YFINANCE_FILL_RATE_LIMIT}
      - IEX_FILL_RATE_LIMIT=${IEX_FILL_RATE_LIMIT}
      - QUANDL_FILL_RATE_LIMIT=${QUANDL_FILL_RATE_LIMIT}
      - QUEUE_1=${QUEUE_1}
      - QUEUE_2=${QUEUE_2}
      - QUEUE_3=${QUEUE_3}
      - QUEUE_4=${QUEUE_4}
      - QUEUE_5=${QUEUE_5}
      - QUEUE_6=${QUEUE_6}
      - QUEUE_7=${QUEUE_7}
      - QUEUE_8=${QUEUE_8}
      - QUEUE_9=${QUEUE_9}
      - QUEUE_10=${QUEUE_10}
      - ENABLE_LOGGING=${ENABLE_LOGGING}
      - LOG_LEVEL=${LOG_LEVEL}
      - CLOUD_LOGGING_ENABLED=${CLOUD_LOGGING_ENABLED}
      - CLOUD_LOGGING_ENDPOINT=${CLOUD_LOGGING_ENDPOINT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - ENABLE_RETRY=${ENABLE_RETRY}
      - ENABLE_BACKFILL=${ENABLE_BACKFILL}
      - POLL_TIMEOUT=${POLL_TIMEOUT}
      - MAX_API_CALLS_PER_MIN=${MAX_API_CALLS_PER_MIN}
      - QUEUE_TYPE=${QUEUE_TYPE}
      - SQS_QUEUE_URL=${SQS_QUEUE_URL}
    restart: always
    volumes:
      - .:/app
