version: "3.8"

services:
  poller:
    build: .
    container_name: stock_data_poller  
    restart: always
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root
      - POLLER_TYPE=yfinance
      - QUEUE_TYPE=rabbitmq
      - SYMBOLS=AAPL,TSLA,GOOGL
      - RABBITMQ_HOST=localhost
      - RABBITMQ_EXCHANGE=stock_data_exchange
      - RABBITMQ_ROUTING_KEY=stock_data
      - SQS_QUEUE_URL=
      - POLL_INTERVAL=60
      - REQUEST_TIMEOUT=30
      - MAX_RETRIES=5
      - RETRY_DELAY=5
      - LOG_LEVEL=info
      - FINNHUB_FILL_RATE_LIMIT=100
      - POLYGON_FILL_RATE_LIMIT=100
      - ALPHA_VANTAGE_FILL_RATE_LIMIT=100
      - YFINANCE_FILL_RATE_LIMIT=100
      - IEX_FILL_RATE_LIMIT=100
      - QUANDL_FILL_RATE_LIMIT=100
      - ENABLE_LOGGING=true
      - CLOUD_LOGGING_ENABLED=false
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_REGION=us-east-1
      - ENABLE_RETRY=true
      - ENABLE_BACKFILL=false
      - POLL_TIMEOUT=30
      - MAX_API_CALLS_PER_MIN=1000
    networks:
      - stock_poller_network  

networks:
  stock_poller_network:  
    driver: bridge
