version: "3.8"

services:
  vault:
    image: hashicorp/vault:1.13.3
    container_name: vault
    restart: always
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK

  vault-init:
    image: curlimages/curl
    container_name: vault_init
    depends_on:
      - vault
    entrypoint: ["/bin/sh", "-c", "/vault-init.sh"]
    volumes:
      - ./vault-init.sh:/vault-init.sh

  poller:
