apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock_data_poller
  labels:
    app: stock_data_poller
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: stock_data_poller
  template:
    metadata:
      labels:
        app: stock_data_poller
    spec:
      containers:
        - name: stock_data_poller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
