version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    deploy:
      replicas: 3  # Scale RabbitMQ with 3 replicas
      resources:
        limits:
          cpus: "1"
          memory: "1G"
      placement:
        constraints: [node.role == worker]  # Ensure services run on worker nodes
    environment:
      RABBITMQ_ERLANG_COOKIE: "shared_erlang_cookie_secret"
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: securepassword
      RABBITMQ_NODENAME: rabbit@rabbitmq
      RABBITMQ_CLUSTER_PARTITION_HANDLING: autoheal
      RABBITMQ_HIPE_COMPILE: "1"
      RABBITMQ_LOGS: "/var/log/rabbitmq/rabbit.log"
    ports:
      - "15672:15672"  # Management console
      - "5672:5672"    # AMQP port
      - "25672:25672"  # Cluster communication
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq_definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    networks:
      - rabbitmq_net

  redis:
    image: bitnami/redis:7.2
    deploy:
      replicas: 3  # Scale Redis with 3 replicas
      resources:
        limits:
          cpus: "1"
          memory: "1G"
    environment:
      ALLOW_EMPTY_PASSWORD: "no"
      REDIS_PASSWORD: redispassword
      REDIS_REPLICATION_MODE: "master"
      REDIS_LOGLEVEL: "notice"
    ports:
      - "6379:6379"  # Redis master port
    volumes:
      - redis_data:/bitnami/redis/data
    networks:
      - redis_net

  redis-replica:
    image: bitnami/redis:7.2
    deploy:
      replicas: 2  # You can add more replicas if needed
    environment:
      ALLOW_EMPTY_PASSWORD: "no"
      REDIS_PASSWORD: redispassword
      REDIS_REPLICATION_MODE: "replica"
      REDIS_MASTER_HOST: redis
      REDIS_MASTER_PASSWORD: redispassword
    ports:
      - "6380:6379"  # Redis replica port
    volumes:
      - redis_replica_data:/bitnami/redis/data
    networks:
      - redis_net

  redis-sentinel:
    image: bitnami/redis-sentinel:7.2
    deploy:
      replicas: 3  # Sentinels for high availability
      resources:
        limits:
          cpus: "0.5"
          memory: "500M"
    environment:
      REDIS_MASTER_HOST: redis
      REDIS_MASTER_PASSWORD: redispassword
      REDIS_SENTINEL_QUORUM: "2"
      REDIS_SENTINEL_PASSWORD: "sentinelpassword"
    ports:
      - "26379:26379"  # Sentinel port
    volumes:
      - ./sentinel.conf:/opt/bitnami/redis-sentinel/etc/sentinel.conf
    command: redis-sentinel /opt/bitnami/redis-sentinel/etc/sentinel.conf
    networks:
      - redis_net

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "8001:8001"  # RedisInsight UI port
    environment:
      REDIS_URL: redis://redis:6379
    networks:
      - redis_net

volumes:
  rabbitmq_data:
  redis_data:
  redis_replica_data:

networks:
  rabbitmq_net:
  redis_net:
