apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stock_data_poller-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/my-org/stock_data_poller.git
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
