apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stock_data_poller
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/my-org/stock_data_poller.git
    path: charts/stock_data_poller
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
