name: Helm Dry-Run Deployment

on: [push, pull_request]

jobs:
  helm-dry-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.3 # or your preferred stable version

      - name: Set Up Kubernetes (Kind)
        uses: helm/kind-action@v1

      - name: Helm Install (Dry Run)
        run: |
          helm install test-release charts/stock_data_poller/ --dry-run --debug
