name: Helm Chart Linting

on:
  pull_request:
  push:
    branches: [main]

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Helm lint
        run: |
          helm lint charts/${{ github.event.repository.name }}
